# This file is part of the Sylius package.
# (c) Sylius Sp. z o.o.

default:
    suites:
        api_managing_promotion_coupons:
            contexts:
                - sylius.behat.context.hook.doctrine_orm

                - sylius.behat.context.transform.coupon
                - sylius.behat.context.transform.promotion
                - sylius.behat.context.transform.shared_storage

                - sylius.behat.context.setup.channel
                - sylius.behat.context.setup.promotion
                - sylius.behat.context.setup.admin_api_security

                - sylius.behat.context.api.admin.managing_promotion_coupons

            filters:
                tags: "@managing_promotion_coupons&&@api"
            javascript: false
